### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by peterdesmet** [Canadensys/norms-for-data-use#1]
@dbloom, you sent me an email regarding renaming your fork of this repository, but I must have deleted it somehow and I can't find it back.

I think you can rename your fork without any problem: 1) the link to the original Canadensys repository will stay intact and 2) any links in the wild to your repo (but there aren't probably any yet) will automatically redirect. I have already renamed [this forked repo](https://github.com/LifeWatchINBO/eurasian-spoonbill) without problems, but you might want to check the GitHub documentation to be sure.

@dshorthouse, maybe we should rename this repo to `norms` or `norms-for-data-use`, so it provides a better name for forked repos. The link back includes 'Canadensys' anyway: see https://github.com/VertNet/canadensys-norms. What do you think?

**Comment by dshorthouse** [comment]
Done. The repo is now called norms-for-data-use as you can see.

**Comment by peterdesmet** [comment]
Great! :bear:

**Comment by dbloom** [comment]
Great.

I'll delete my fork and repo and start anew with this new name.

d
